server:
  port: 8080
  servlet:
    context-path: /catalog

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always