server:
   port: 8761
spring:
  application:
    name: discovery   
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      #this application will be Eureka server.. it shouldn't reigster itself
      registerWithEureka: false
      fetchRegistry: false
