#test properties for hierarchy validation.. check application.yml
test:
   prop:
      one: x
      three: zz

#config for Eureka server lookup
server:
   port: 8080
eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/discovery/eureka}
   instance:
      preferIpAddress: true
